// GENERATED by scripts/mirror-card-art.ts — do not edit by hand.
//
// Cards whose art the RiftScribe CDN no longer serves at ANY rendition, so
// there is nothing for public/card-art/ to mirror. lib/card-image-url.ts
// returns null for these, which makes CardImage fall back to its generated
// CardArt instead of emitting an <img> that 404s.
//
// This ships in the client bundle (CardImage is pulled in by QuickView and
// SellForm), which is the whole reason the main URL rewrite is a pure string
// function with no lookup table: a short exception list costs a couple of KB,
// a full 950-entry table would not be worth it. tests/card-image-url.test.ts
// caps how long this may get.
//
// Re-run the mirror to refresh it: npx tsx scripts/mirror-card-art.ts
export const MISSING_CARD_ART: ReadonlySet<string> = new Set([
  "unl-055a-219-bde73d52abbc1f36",
]);
