// Where a card's picture comes from, in one place.
//
// ── The outage this exists for ───────────────────────────────────────────────
// Card art was hosted by RiftScribe. Every card row carries TWO of their URLs,
// written by prisma/seed.ts and scripts/sync-cards.ts out of the upstream
// dataset (prisma/riftbound-cards.json):
//
//   imageUrl       https://cdn.riftscribe.gg/cards/originals/<stem>.png
//   imageThumbUrl  https://cdn.riftscribe.gg/cards/thumbnails/large/<stem>.webp
//
// In September 2026 the CDN dropped the `originals/` tree — every one of those
// PNGs 404s, for every card in every set (OGN, OGS, SFD, UNL) — and
// `thumbnails/medium/` with it. Nothing in our database changed, so the `??`
// fallbacks that used to make missing art degrade gracefully never fired:
// `imageUrl` is non-null, it is simply dead. `riftscribe.gg` itself now 404s
// too, so this reads as a site being wound down rather than a path reshuffle.
//
// ── We serve our own copy now ────────────────────────────────────────────────
// Rewriting onto whichever rendition still answered fixed the outage and left
// us exactly as exposed to the next deletion. So scripts/mirror-card-art.ts
// mirrors every card into `public/card-art/<stem>.webp`, keeping the CDN's own
// filename stem, and `cardImageSrc` — which every render path goes through —
// maps any RiftScribe card URL onto that copy with pure string work.
//
// PURE STRING WORK IS THE REQUIREMENT, not an implementation detail. CardImage
// is pulled into the client bundle by its client-component callers (QuickView,
// SellForm), so anything this module imports ships to the browser: a lookup
// table of 950 mirrored stems would be ~33 KB of dead JavaScript on every page.
// The rewrite is therefore UNCONDITIONAL, and what makes that safe is coverage:
// tests/card-image-url.test.ts fails unless every card in the dataset has a
// mirrored file. Refresh the dataset without re-running the mirror and that
// test goes red — which is the point.
//
// The one exception list is src/lib/card-art-missing.ts: 71 cards whose art the
// CDN no longer has at any size, generated by the same script. Those report no
// picture at all, so CardImage draws its generated CardArt — the behaviour an
// artless card has always had — rather than linking to a 404.
//
// Anything that is not a RiftScribe card URL is returned untouched: the
// Vendetta signature prints in prisma/manual-cards.json are re-hosted BY US at
// riftcompare.com/signature-cards/*.jpg, they are genuinely full-resolution,
// and `full` callers must keep getting them.
//
// ── Why the importers still write the CDN URL ────────────────────────────────
// `liveCardImage` (the CDN-to-CDN repair) is what prisma/seed.ts and
// scripts/sync-cards.ts use, so the database keeps recording where a card's art
// actually came from. Serving our mirror is a presentation decision, made here,
// on read — which is also why a card whose mirror is missing can be fixed by
// re-running one script instead of by a migration.

import { MISSING_CARD_ART } from "./card-art-missing";
import { SITE_URL } from "./site";

const CDN_CARDS = "https://cdn.riftscribe.gg/cards/";
const DEAD_ORIGINALS = `${CDN_CARDS}originals/`;
const LIVE_LARGE = `${CDN_CARDS}thumbnails/large/`;

/** Our mirror, relative to the site root — scripts/mirror-card-art.ts fills it. */
export const MIRROR_PREFIX = "/card-art/";

// Every shape the CDN has ever served a card under, and nothing else. Matching
// the WHOLE URL rather than popping a basename is deliberate: an unexpected
// path (a deeper tree, a rendition we have never mirrored) must be refused
// outright, not flattened onto a filename we would then link to blindly.
const CDN_CARD_RE = /^https:\/\/cdn\.riftscribe\.gg\/cards\/(?:originals|thumbnails\/(?:small|medium|large))\/([a-z0-9][a-z0-9-]*)\.[a-z0-9]+$/i;

/** The CDN's filename stem, which mirror-card-art.ts reuses as our filename. */
function stemOf(url: string): string | null {
  return CDN_CARD_RE.exec(url)?.[1] ?? null;
}

/**
 * One CDN URL in, one CDN URL that actually resolves out.
 *
 * A dead `originals/<stem>.png` becomes `thumbnails/large/<stem>.webp`;
 * anything else is returned as-is. Used on the WRITE path (the importers), so
 * the database never stores a URL the CDN has deleted. Read paths want
 * `cardImageSrc`, which serves our own mirror instead.
 */
export function liveCardImage(url: string | null | undefined): string | null {
  if (!url) return null;
  if (!url.startsWith(DEAD_ORIGINALS)) return url;
  const stem = stemOf(url);
  return stem ? `${LIVE_LARGE}${stem}.webp` : null;
}

/** Maps a RiftScribe card URL onto our mirrored copy; passes anything else through. */
function mirrored(url: string | null | undefined): string | null {
  if (!url) return null;
  if (!url.startsWith(CDN_CARDS)) return url;
  const stem = stemOf(url);
  // 71 cards went down with the CDN's art entirely — nothing to mirror, so they
  // report "no picture" and CardImage draws its generated CardArt instead of
  // linking to a 404. See src/lib/card-art-missing.ts.
  if (!stem || MISSING_CARD_ART.has(stem)) return null;
  return `${MIRROR_PREFIX}${stem}.webp`;
}

export interface CardImageUrls {
  imageUrl?: string | null;
  imageThumbUrl?: string | null;
}

export interface CardImageOpts {
  /** Prefer the largest rendition (the card-detail hero, OG art, JSON-LD). */
  full?: boolean;
  /**
   * Return an absolute URL. REQUIRED wherever the value leaves the page: satori
   * (`ImageResponse`) cannot fetch a site-relative src, and JSON-LD, the image
   * sitemap and the public API are all read by machines with no page context.
   */
  absolute?: boolean;
}

/**
 * The best URL to render a card with, or null when the card has no picture at
 * all (callers fall back to generated CardArt).
 *
 * For RiftScribe cards both modes land on our mirror — one file per card, and
 * at 744x1039 it is larger than any slot on the site, hero included. For art we
 * re-host ourselves the two modes still differ, because there the full-size
 * file and the thumbnail are genuinely different images.
 */
export function cardImageSrc(card: CardImageUrls, opts: CardImageOpts = {}): string | null {
  const main = mirrored(card.imageUrl);
  const thumb = mirrored(card.imageThumbUrl);
  const src = opts.full ? main ?? thumb : thumb ?? main;
  if (!src || !opts.absolute) return src;
  return src.startsWith("/") ? `${SITE_URL}${src}` : src;
}
