import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";

// ─────────────────────────────────────────────────────────────────────────────
// The Trade Gremlin roast (TradeCalculator.tsx) used to label itself with a
// "✨ Live AI" / "Beta" chip pair keyed off the response source, which was
// removed because it announced which code path had run — something a reader
// cannot act on — without actually disclosing that the roast text itself is
// AI-generated. Removing the badge without adding real disclosure would have
// turned a labelled AI feature into an unlabelled one, so the footer gained a
// proper line instead. This pins both directions so a later "remove every AI
// mention" pass can't silently drop the disclosure along with the badge.
// ─────────────────────────────────────────────────────────────────────────────

const read = (p: string) => readFileSync(join(process.cwd(), p), "utf8");

/** Strip // and /* comments so historical notes don't read as live UI copy. */
function code(src: string): string {
  return src.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/.*$/gm, "");
}

test("the Trade Gremlin no longer renders a Live AI / Beta badge pair", () => {
  const src = code(read("src/components/TradeCalculator.tsx"));
  assert.doesNotMatch(src, /Live AI/, "TradeCalculator.tsx still renders a \"Live AI\" badge");
  assert.doesNotMatch(
    src,
    /source === "ai" \?/,
    "TradeCalculator.tsx still branches on the AI code path to render a label",
  );
});

test("the Trade Gremlin roast discloses AI authorship", () => {
  // This had NO disclosure at all — the "Live AI" badge was doing that job by
  // accident. Removing the badge without adding fine print would have turned a
  // labelled AI feature into an unlabelled one.
  const src = code(read("src/components/TradeCalculator.tsx"));
  assert.match(src, /generated by AI for fun/i, "the roast must disclose that it is AI-written");
});
