import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";

// ─────────────────────────────────────────────────────────────────────────────
// Where "AI" may and may not appear in the UI.
//
// Two rules, pulling in opposite directions, which is why they need pinning:
//
//   1. NOT IN A HEADING OR BADGE. "AI Tips" and the "Live AI" / "Beta" chips put
//      the implementation in the headline of modules whose actual subject is a
//      card's price or a trade's fairness. They also told the reader which code
//      path had run — something they cannot act on.
//
//   2. YES IN THE DISCLOSURE. The prose in both modules is genuinely LLM-written
//      when a key is set (lib/ai-insight.ts). Dropping the fine print would leave
//      AI-generated commentary undisclosed, which is the thing ad reviewers mark
//      down — disclosed AI commentary is not. Renaming a panel and disclosing
//      authorship are not in tension, and a future "remove every AI mention"
//      sweep must not quietly delete rule 2 while satisfying rule 1.
// ─────────────────────────────────────────────────────────────────────────────

const read = (p: string) => readFileSync(join(process.cwd(), p), "utf8");

/** Strip // and /* comments so historical notes don't read as live UI copy. */
function code(src: string): string {
  return src.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/.*$/gm, "");
}

const PANELS = ["src/components/PriceTake.tsx", "src/components/TradeCalculator.tsx"];

test("no user-facing heading or badge says AI", () => {
  for (const f of PANELS) {
    const src = code(read(f));
    assert.doesNotMatch(src, /Live AI/, `${f} still renders a "Live AI" badge`);
    assert.doesNotMatch(src, /AI Tips/, `${f} still renders the old "AI Tips" heading`);
    // The badge pair keyed off `source` existed only to label the code path.
    assert.doesNotMatch(
      src,
      /source === "ai" \?/,
      `${f} still branches on the AI code path to render a label`,
    );
  }
});

test("the Price Take panel is named without AI and still discloses it", () => {
  const src = read("src/components/PriceTake.tsx");
  assert.match(src, /const PANEL_TITLE = "Price Take";/, "the heading constant must be the new name");
  // Rule 2. Specific wording, not just the letters "AI": the disclosure has to
  // name AI as the author, not merely say "automatically generated".
  assert.match(
    code(src),
    /Generated by AI for fun — not financial advice/,
    "the AI authorship disclosure must survive the rename",
  );
});

test("the Trade Gremlin roast discloses AI authorship too", () => {
  // This one had NO disclosure at all — the "Live AI" badge was doing that job by
  // accident. Removing the badge without adding fine print would have turned a
  // labelled AI feature into an unlabelled one.
  const src = code(read("src/components/TradeCalculator.tsx"));
  assert.match(src, /generated by AI for fun/i, "the roast must disclose that it is AI-written");
});

test("the component file no longer carries the old name either", () => {
  // A stale `AiInsight` export is how "AI" gets typed back into the heading by
  // the next person to touch the file.
  for (const f of ["src/components/QuickView.tsx", "src/app/card/[id]/page.tsx"]) {
    const src = read(f);
    assert.doesNotMatch(src, /from "\.\/AiInsight"|from "@\/components\/AiInsight"/, `${f} imports the old module`);
    assert.match(src, /PriceTake/, `${f} must render the renamed component`);
  }
});

test("the AdSense gate is not loosened by the rename alone", () => {
  // The module was hidden for three reasons; the rename removes exactly one of
  // them. It comments on price direction and reads as quasi-financial advice
  // regardless of what the heading says, so it stays gated until approval.
  const page = read("src/app/card/[id]/page.tsx");
  assert.match(
    page,
    /\{!ADSENSE_REVIEW_MODE && \(\s*<section[^>]*>\s*<PriceTake/,
    "Price Take must still be gated behind ADSENSE_REVIEW_MODE",
  );
});
