import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { cardImageSrc, liveCardImage, MIRROR_PREFIX } from "../src/lib/card-image-url";
import { MISSING_CARD_ART } from "../src/lib/card-art-missing";
import { SITE_URL } from "../src/lib/site";
import { MAX_BYTES } from "../scripts/image-budget";

// ─────────────────────────────────────────────────────────────────────────────
// Card art stopped rendering across the whole site in September 2026: the
// RiftScribe CDN dropped its `cards/originals/` tree (and `thumbnails/medium/`
// with it), and every Card row still stores one of those PNG URLs in
// `imageUrl`. Nothing was null, so every `imageUrl ?? imageThumbUrl` fallback
// in the codebase happily picked the dead URL — the card-detail hero, the
// article close-ups, the OG unfurls, the JSON-LD `image`, the image sitemap and
// the public API all pointed at a 404.
//
// The site now serves its OWN copy of every card (public/card-art, filled by
// scripts/mirror-card-art.ts), and lib/card-image-url.ts is the one place that
// maps a stored URL onto it. That rewrite is unconditional — it has to be, so
// the helper stays a pure string function safe to ship in the client bundle —
// so the coverage test below is what makes it safe: every card in the dataset
// must have a mirrored file.
// ─────────────────────────────────────────────────────────────────────────────

const ROOT = process.cwd();
const CDN = "https://cdn.riftscribe.gg/cards/";
const DEAD = `${CDN}originals/`;
const LARGE = `${CDN}thumbnails/large/`;
const MIRROR_DIR = join(ROOT, "public/card-art");

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else if (/\.(ts|tsx)$/.test(entry)) out.push(p);
  }
  return out;
}

test("every card in the dataset either has a mirrored file or is a known-missing one", () => {
  // The rewrite is unconditional, so a card the mirror skipped would render a
  // 404. This is the guard that makes that design safe.
  const cards: { id: string; image?: string; image_thumb?: { small?: string; large?: string } }[] = JSON.parse(
    readFileSync(join(ROOT, "prisma/riftbound-cards.json"), "utf8")
  );
  assert.ok(cards.length > 900, `expected the full catalogue, found ${cards.length}`);
  const unmirrored: string[] = [];
  let artless = 0;
  for (const c of cards) {
    const url = c.image_thumb?.large ?? c.image_thumb?.small ?? c.image;
    if (!url) continue;
    const local = cardImageSrc({ imageUrl: url });
    if (local === null) {
      // Art the CDN no longer has: renders as generated CardArt, by design.
      artless++;
      continue;
    }
    assert.ok(local.startsWith(MIRROR_PREFIX), `${c.id} does not resolve to the mirror (${local})`);
    if (!existsSync(join(ROOT, "public", local.slice(1)))) unmirrored.push(c.id);
  }
  assert.deepEqual(
    unmirrored.slice(0, 10),
    [],
    `${unmirrored.length} cards have no mirrored file — run: npx tsx scripts/mirror-card-art.ts`
  );
  assert.equal(artless, MISSING_CARD_ART.size, "every recorded missing stem should belong to a catalogued card");
});

test("the missing-art list stays an exception list, not the lookup table we refused to ship", () => {
  // It rides in the client bundle. A few dozen stems is a couple of KB; a list
  // that grew towards the full catalogue would mean the mirror is broken, and
  // would be exactly the payload lib/card-image-url.ts exists to avoid.
  assert.ok(MISSING_CARD_ART.size < 150, `${MISSING_CARD_ART.size} missing stems — re-run the mirror before shipping this`);
  const src = readFileSync(join(ROOT, "src/lib/card-art-missing.ts"), "utf8");
  assert.match(src, /GENERATED by scripts\/mirror-card-art\.ts/);
});

test("no mirrored file busts the image budget that scripts/check-images.ts enforces", () => {
  const over = readdirSync(MIRROR_DIR)
    .filter((f) => f.endsWith(".webp"))
    .filter((f) => statSync(join(MIRROR_DIR, f)).size > MAX_BYTES);
  assert.deepEqual(over, [], "mirror-card-art.ts should have re-encoded these down");
});

test("both CDN paths — the dead one and the surviving one — map onto our copy", () => {
  const stem = "ogn-029-298-723927dee729ccc5";
  assert.equal(cardImageSrc({ imageUrl: `${DEAD}${stem}.png` }), `${MIRROR_PREFIX}${stem}.webp`);
  assert.equal(cardImageSrc({ imageThumbUrl: `${LARGE}${stem}.webp` }), `${MIRROR_PREFIX}${stem}.webp`);
  // Star/variant stems and every set prefix go through the same stem swap.
  const star = "unl-228-star-219-0fceb798b48de9c4";
  assert.equal(cardImageSrc({ imageUrl: `${DEAD}${star}.png` }), `${MIRROR_PREFIX}${star}.webp`);
});

test("art we host ourselves is never rewritten, and `full` still means full-size there", () => {
  const ours = {
    imageUrl: "https://riftcompare.com/signature-cards/ven-001.jpg",
    imageThumbUrl: "https://riftcompare.com/signature-cards/ven-001-480w.webp",
  };
  assert.equal(cardImageSrc(ours, { full: true }), ours.imageUrl);
  assert.equal(cardImageSrc(ours), ours.imageThumbUrl);
  assert.equal(cardImageSrc({ imageUrl: "data:image/jpeg;base64,abc" }), "data:image/jpeg;base64,abc");
});

test("a card with no art at all returns null, so CardImage falls back to generated CardArt", () => {
  assert.equal(cardImageSrc({ imageUrl: null, imageThumbUrl: null }), null);
  assert.equal(cardImageSrc({}), null);
  // A stem that would escape the mirror directory is refused rather than built.
  assert.equal(cardImageSrc({ imageUrl: `${DEAD}nested/ogn-001.png` }), null);
  assert.equal(cardImageSrc({ imageUrl: CDN }), null);
});

test("`absolute` makes the URL safe to hand to satori, JSON-LD, the sitemap and the public API", () => {
  const stem = "sfd-114-221-41e857f6194065be";
  assert.equal(
    cardImageSrc({ imageUrl: `${DEAD}${stem}.png` }, { full: true, absolute: true }),
    `${SITE_URL}${MIRROR_PREFIX}${stem}.webp`
  );
  // Already-absolute art is not double-prefixed.
  const ours = "https://riftcompare.com/signature-cards/ven-001.jpg";
  assert.equal(cardImageSrc({ imageUrl: ours }, { full: true, absolute: true }), ours);
  assert.equal(cardImageSrc({}, { absolute: true }), null);
});

test("the write path still records where the art came from, repairing only the dead prefix", () => {
  const stem = "ogn-001-298-8de89b4b8fb3186d";
  assert.equal(liveCardImage(`${DEAD}${stem}.png`), `${LARGE}${stem}.webp`);
  assert.equal(liveCardImage(`${LARGE}${stem}.webp`), `${LARGE}${stem}.webp`);
  assert.equal(liveCardImage("https://riftcompare.com/signature-cards/ven-001.jpg"), "https://riftcompare.com/signature-cards/ven-001.jpg");
  assert.equal(liveCardImage(null), null);
  assert.equal(liveCardImage(undefined), null);
  assert.equal(liveCardImage(`${DEAD}nested/x.png`), null);
});

test("no source file hard-codes the dead CDN path (articles included)", () => {
  const offenders: string[] = [];
  for (const f of [...walk(join(ROOT, "src")), join(ROOT, "prisma/seed.ts")]) {
    // The rewrite rule itself is where the prefix is allowed to be named.
    if (f.endsWith(join("lib", "card-image-url.ts"))) continue;
    if (readFileSync(f, "utf8").includes("cards/originals/")) offenders.push(f.slice(ROOT.length + 1));
  }
  assert.deepEqual(offenders, [], `hard-coded dead card-art URLs: ${offenders.join(", ")}`);
});

test("every card render path goes through the helper rather than reading imageUrl raw", () => {
  const mustUse = [
    "src/components/CardImage.tsx",
    "src/components/ArticleView.tsx",
    "src/components/DeckBuilder.tsx",
    "src/app/opengraph-image.tsx",
    "src/app/card/[id]/opengraph-image.tsx",
    "src/app/c/[token]/opengraph-image.tsx",
    "src/app/card/[id]/page.tsx",
    "src/app/api/card/[id]/route.ts",
    "src/lib/sitemap-sections.ts",
    "src/lib/public-api.ts",
  ];
  for (const rel of mustUse) {
    const src = readFileSync(join(ROOT, rel), "utf8");
    assert.match(src, /from "(@\/lib|\.)\/card-image-url"/, `${rel} must resolve card art through lib/card-image-url`);
    // …and must not read the raw column back out for rendering. (A Prisma
    // `imageUrl: true` select line is fine — that's how the helper gets fed.)
    const raw = src
      .split("\n")
      .filter((l) => /\.imageUrl\b/.test(l) && !/liveCardImage|cardImageSrc|^\s*\/\//.test(l));
    assert.deepEqual(raw, [], `${rel} still reads .imageUrl directly: ${raw.join(" | ")}`);
  }
});

test("anything that leaves the page asks for an absolute URL", () => {
  // satori can't fetch a site-relative src, and JSON-LD / the sitemap / the
  // public API are read by machines with no page to resolve against.
  for (const rel of [
    "src/app/opengraph-image.tsx",
    "src/app/card/[id]/opengraph-image.tsx",
    "src/app/c/[token]/opengraph-image.tsx",
    "src/app/card/[id]/page.tsx",
    "src/app/api/card/[id]/route.ts",
    "src/lib/sitemap-sections.ts",
    "src/lib/public-api.ts",
  ]) {
    const src = readFileSync(join(ROOT, rel), "utf8");
    const calls = src.match(/cardImageSrc\([^)]*\)/g) ?? [];
    assert.ok(calls.length > 0, `${rel} makes no cardImageSrc call`);
    for (const c of calls) assert.match(c, /absolute: true/, `${rel}: ${c} must pass absolute: true`);
  }
});

test("the importers stop writing URLs the CDN no longer serves", () => {
  for (const rel of ["prisma/seed.ts", "scripts/sync-cards.ts"]) {
    const src = readFileSync(join(ROOT, rel), "utf8");
    assert.match(src, /imageUrl: liveCardImage\(c\.image\)/, `${rel} must normalise imageUrl on write`);
    // `medium` is gone too; `small` is the only other surviving rendition.
    assert.doesNotMatch(src, /image_thumb\?\.medium/, `${rel} must not fall back to the dead medium thumbnail`);
  }
});
