import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { OAUTH_PROVIDERS } from "../src/lib/oauth";
import { METHODOLOGY_BREAKS } from "../src/lib/methodology-breaks";

// ─────────────────────────────────────────────────────────────────────────────
// The trust and policy pages (/about, /editorial-policy, /methodology,
// /privacy, /terms, /contact, /support) describe the site to the people most
// likely to check it: a reviewer after a "low value content" rejection, and a
// buyer deciding whether to trust a number. Rewritten 2026-09-26 ("Blog and
// tools, joined up" in DECISIONS.md) because several of their claims no longer
// matched the code — a password sign-in, a removed marketplace, "the whole
// catalogue" searched on eBay daily, history "per market per day".
//
// These tests pin every figure the pages TYPE to the constant that produces it,
// so a change to the importer, a threshold or a cookie fails here rather than
// leaving the policy quietly wrong. Numbers the pages COMPUTE (store counts
// from RETAILER_LIST, the FX table from USD_TO, the probe's addresses from the
// postage snapshot) are asserted to stay computed.
// ─────────────────────────────────────────────────────────────────────────────

const ROOT = process.cwd();
const read = (p: string) => readFileSync(join(ROOT, p), "utf8");
// Comments explain what USED to be claimed; strip them so a removed claim named
// in a note does not read as copy. Line comments first (a "/card/*"-shaped
// string in a // note would otherwise open a block comment), keeping URLs.
const code = (p: string) => read(p).replace(/(^|[^:])\/\/.*$/gm, "$1").replace(/\/\*[\s\S]*?\*\//g, "");
// JSX wraps sentences across lines; collapse whitespace so a sentence matches whole.
const text = (p: string) => code(p).replace(/\s+/g, " ");

const ABOUT = "src/app/about/page.tsx";
const POLICY = "src/app/editorial-policy/page.tsx";
const METHOD = "src/app/methodology/page.tsx";
const PRIVACY = "src/app/privacy/page.tsx";
const TERMS = "src/app/terms/page.tsx";
const CONTACT = "src/app/contact/page.tsx";
const SUPPORT = "src/app/support/page.tsx";
const TRUST_PAGES = [ABOUT, POLICY, METHOD, PRIVACY, TERMS, CONTACT, SUPPORT];

/** The right-hand side of `name = …` in a source file, trimmed. */
function constant(file: string, name: string): string {
  const m = new RegExp(`\\b${name}\\s*(?::[^=]+)?=\\s*([^;\\n]+)`).exec(read(file));
  assert.ok(m, `${file} no longer defines ${name} — re-derive what the trust pages say about it`);
  return m[1].trim();
}
const num = (file: string, name: string) => Number(constant(file, name).replace(/_/g, ""));

// ── Authorship ────────────────────────────────────────────────────────────────

// The owner's own wording (2026-09-26). It replaced "written by people", which
// the repo's records did not support and the rejection ("may be generated by
// AI") made a liability.
const AUTHORSHIP =
  "Articles are drafted with AI assistance, then edited and fact-checked by Bill before publishing; " +
  "prices and figures come from RiftCompare&rsquo;s own price database, never from the draft.";

test("the owner's authorship statement is on /about and /editorial-policy, word for word", () => {
  for (const f of [ABOUT, POLICY]) {
    assert.ok(text(f).includes(AUTHORSHIP), `${f} must carry the owner-confirmed authorship sentence`);
    assert.doesNotMatch(text(f), /written by (the )?people|human-written/i, `${f} overclaims human authorship`);
  }
});

test("the one request-time AI feature is named, and it is the one the code labels", () => {
  const policy = text(POLICY);
  assert.match(policy, /Trade Gremlin/);
  assert.match(policy, /href="\/trade"/);
  // It is the only live model call a visitor can trigger…
  assert.match(read("src/app/api/trade-roast/route.ts"), /llmText\(/);
  // …and it is labelled where it appears (tests/ai-labelling.test.ts pins the wording).
  assert.match(code("src/components/TradeCalculator.tsx"), /generated by AI for fun/i);
});

// ── /about ────────────────────────────────────────────────────────────────────

test("/about says who runs the site, and its structured data names the founder", () => {
  const about = text(ABOUT);
  assert.match(about, /id="who-runs-riftcompare"/);
  assert.match(about, /built and run by one person/);
  assert.match(about, /href="\/authors\/bill"/);
  const src = read(ABOUT);
  assert.match(src, /"@type": "AboutPage"/);
  assert.match(src, /mainEntity: \{[\s\S]*?"@id": `\$\{SITE_URL\}\/#org`[\s\S]*?founder: \{ "@type": "Person", "@id": `\$\{SITE_URL\}\/authors\/bill#author`, name: "Bill"/);
  // The same Person node the articles under his byline carry.
  assert.match(read("src/lib/content/authors.ts"), /"@id": `\$\{SITE_URL\}\/authors\/\$\{a\.slug\}#author`/);
  assert.match(read("src/lib/content/authors.ts"), /slug: "bill",\s*name: "Bill",\s*type: "Person"/);
  assert.match(src, /dateModified: STATIC_PAGE_DATES\["\/about"\]/);
});

test("/about counts stores from RETAILER_LIST and drops the stale lines", () => {
  const about = text(ABOUT);
  assert.match(about, /RETAILER_LIST\.length/);
  assert.doesNotMatch(about, /\b\d{2,3} (stores|retailers)\b/, "a typed store count drifts — compute it");
  assert.doesNotMatch(about, /dozens of stores|no account required|several times a day|daily snapshots|what you'd actually pay|what you&rsquo;d actually pay/i);
  // The launch post that /about replaced is still redirected here.
  assert.match(read("next.config.js"), /source: "\/blog\/welcome-to-riftcompareau", destination: "\/about"/);
});

test("/about lists every way the site earns and links the pages that explain it", () => {
  const about = text(ABOUT);
  for (const s of ["Google AdSense", "eBay Partner Network", "Impact", "Amazon Associate", "TIER_NAMES.plus", "TIER_NAMES.premium", 'href="/stores/consulting"']) {
    assert.ok(about.includes(s), `/about must name ${s}`);
  }
  for (const href of ["/editorial-policy", "/methodology", "/blog", "/guides", "/tools", "/stores/tracked"]) {
    assert.ok(about.includes(`href="${href}"`), `/about must link ${href}`);
  }
});

// ── /editorial-policy ─────────────────────────────────────────────────────────

test("/editorial-policy names every revenue source and discloses consulting as a conflict", () => {
  const policy = text(POLICY);
  for (const s of [
    "Google AdSense",
    "eBay Partner Network",
    "Impact",
    "Amazon Associates",
    "as an Amazon Associate we earn from qualifying purchases",
    "Plus and Premium subscriptions",
    "consulting",
    'href="/stores/consulting"',
    "conflict of interest",
    "booking a session changes nothing about how that store appears or ranks",
  ]) {
    assert.ok(policy.includes(s), `/editorial-policy must say "${s}"`);
  }
  assert.doesNotMatch(policy, /marketplace fees/i, "the peer-to-peer marketplace was removed on 2026-08-26");
  // The consulting page makes the same promise the policy repeats.
  assert.match(text("src/app/stores/consulting/page.tsx"), /changes nothing about how your store ranks/);
});

test("the refresh list matches the importer's real cadence", () => {
  const policy = text(POLICY);
  const workflow = read(".github/workflows/refresh-prices.yml");
  assert.match(workflow, /cron: "0 7 \* \* \*"/);
  assert.match(workflow, /cron: "0 19 \* \* \*"/);
  assert.match(policy, /twice a day, at 07:00 and 19:00 UTC/);

  const importer = read("src/lib/price-import.ts");
  const floor = /EBAY_MIN_VALUE_CENTS \?\? (\d+)/.exec(importer);
  assert.ok(floor, "EBAY_MIN_VALUE_USD_CENTS's default moved");
  assert.equal(Number(floor[1]), 500, "the policy says US$5 — update it with the floor");
  assert.match(policy, /worth at least US\$5 at TCGplayer&rsquo;s US market price/);
  assert.match(importer, /EBAY_SKIP_RARITIES = new Set\(\["Common", "Uncommon"\]\)/);
  assert.match(policy, /commons and uncommons are skipped/);

  const markets = (name: string) =>
    [...new RegExp(`${name}: EbayMarketCfg\\[\\] = \\[([\\s\\S]*?)\\];`).exec(importer)![1].matchAll(/country: "(\w+)"/g)].map((m) => m[1]);
  assert.deepEqual(markets("EBAY_ALWAYS_MARKETS"), ["AU", "US"]);
  assert.deepEqual(markets("EBAY_ROTATING_MARKETS"), ["UK", "SG", "EU"]);
  assert.match(policy, /Australia and the US are searched every day; the UK, Singapore and the EU take turns, one a day/);
  assert.match(importer, /refreshEbayChasePrintings\(ebayMarketsForDay\(ebayDayIndex\(\)\)\)/);
  assert.match(policy, /promo, Signature and overnumbered printings in that day&rsquo;s markets are searched again/);
  assert.match(importer, /retailerName: "eBay US",[\s\S]{0,80}USD_TO\.CAD/);
  assert.match(policy, /Canada&rsquo;s eBay rows are the US results converted to Canadian dollars/);

  // Daily since 2026-10-03 (weekly 2026-08-31 → 10-03): every import writes or
  // replaces the day's file (lib/price-history-store.ts) with no interval gate.
  assert.doesNotMatch(read("src/lib/price-history.ts"), /HISTORY_MIN_INTERVAL_DAYS =/, "an interval gate came back — re-derive what the policy says");
  assert.match(read("src/lib/price-import.ts"), /writeCardHistoryDay\(day, points\)/);
  assert.match(policy, /every day we record each card&rsquo;s cheapest price across the Australian, US, UK and Singapore markets, in US dollars/);
  assert.match(read("src/lib/price-history.ts"), /GLOBAL_LOW_MARKETS: readonly Country\[\] = \["AU", "US", "UK", "SG"\]/);

  assert.match(policy, /STORE_ROWS_MAX_AGE_H \/ 24/, "the stale-row window is computed from STORE_ROWS_MAX_AGE_H");
  assert.doesNotMatch(policy, /whole catalogue is searched once|one recorded point per card per market per day|Index and homepage: hourly/i);
});

test("the corrections policy describes how articles are really retired", () => {
  const policy = text(POLICY);
  assert.match(policy, /permanently redirect its address to the page that now covers the topic/);
  assert.match(policy, /correct the text in place and move its last-updated date/);
  assert.doesNotMatch(policy, /don&rsquo;t quietly delete pieces/);
});

// ── /methodology ──────────────────────────────────────────────────────────────

test("/methodology has a section for every source, rule and tool it promises", () => {
  const src = read(METHOD);
  for (const id of [
    "sources", "matching", "conditions", "references", "currency", "postage", "ordering", "history",
    "tools", "deal-finder", "cheapest-on-ebay", "price-gaps", "rising-cards", "index", "best-basket", "box-ev", "demand-finder",
  ]) {
    assert.match(src, new RegExp(`id="${id}" className="scroll-mt-header`), `#${id} is missing or cannot be scrolled to`);
  }
  const page = text(METHOD);
  for (const href of ["/tools/deal-finder", "/market/records", "/tools/rising", "/market", "/tools/best-basket", "/tools/box-ev", "/tools/demand", "/guides/understanding-the-riftcompare-index-methodology"]) {
    assert.ok(page.includes(`href="${href}"`), `/methodology must link ${href}`);
  }
});

test("Deal Finder's formula and thresholds are the ones lib/arbitrage.ts applies", () => {
  const lib = "src/lib/arbitrage.ts";
  const page = text(METHOD);
  assert.match(read(lib), /\(\(marketCents - priceCents\) \/ marketCents\) \* 1000\) \/ 10/);
  assert.match(page, /% below = \(market price − your price\) ÷ market price<\/strong>, to one decimal place/);
  assert.equal(num(lib, "MIN_BUY_CENTS"), 300);
  assert.equal(num(lib, "MIN_BELOW_CENTS"), 100);
  assert.equal(num(lib, "MAX_BELOW_PCT"), 75);
  assert.match(page, /your price is at least 3\.00 in your currency and at least 1\.00 below the market price; anything more than 75% below is dropped/);
  assert.match(read(lib), /country === "US" && tcgLowUsdCents != null && tcgLowUsdCents <= buyCents/);
  assert.match(page, /In the US a card is also dropped when TCGplayer&rsquo;s own cheapest listing is no dearer/);
});

test("the homepage's Cheapest on eBay rule is the one the ranking applies", () => {
  const lib = "src/lib/arbitrage.ts";
  const page = text(METHOD);
  assert.equal(num(lib, "CHEAPEST_EBAY_MIN_CENTS"), 100);
  assert.equal(num(lib, "CHEAPEST_EBAY_MIN_GAP_CENTS"), 50);
  assert.equal(num(lib, "CHEAPEST_EBAY_MAX_GAP_PCT"), 80);
  assert.match(page, /It must be at least 1\.00, at least 0\.50 cheaper than the cheapest of those sources, and less than 80% cheaper/);
  assert.match(read(lib), /RANKED_NON_STORE_SOURCES: Partial<Record<Country, string\[\]>> = \{ EU: \[CARDTRADER_RETAILER\] \}/);
  assert.match(read(lib), /const EBAY_CROSS_BORDER: Partial<Record<Country, true>> = \{ CA: true \}/);
  assert.match(page, /CardTrader in the EU, and TCGplayer&rsquo;s cheapest listing in the US/);
  assert.match(page, /Canada is left out/);
});

test("cross-market gaps are described as a gap, with the board's real cut-offs", () => {
  const page = text(METHOD);
  assert.equal(num("src/lib/arbitrage.ts", "XREGION_MIN_GAP_PCT"), 20);
  assert.equal(num("src/lib/arbitrage.ts", "XREGION_MIN_HOME_CENTS"), 300);
  assert.equal(num("src/app/market/records/page.tsx", "GAPS_SHOWN"), 10);
  assert.equal(num("src/app/market/records/page.tsx", "GAP_MIN_SAVING_CENTS"), 500);
  assert.match(page, /at least 20% cheaper and your own price is at least 3\.00; the board shows the ten biggest gaps in money, and only those worth at least 5\.00/);
  assert.match(page, /It is a price gap, not a saving/);
  assert.doesNotMatch(page, /\b(profit|arbitrage opportunit|flip)/i);
});

test("Rising Cards and the Index are described from their own code, and never as a forecast", () => {
  const page = text(METHOD);
  const rise = "src/lib/rise-predictor.ts";
  assert.equal(num(rise, "SCAN"), 400);
  assert.equal(num(rise, "MIN_POINTS"), 5);
  assert.equal(num(rise, "OVERHEAT_PCT"), 35);
  assert.match(page, /is a screen, not a prediction/);
  assert.match(page, /up to the 400 most-searched cards/);
  assert.match(page, /The price signals need five weekly points/);
  assert.match(page, /A card already up more than 35% on last week is marked down/);
  assert.doesNotMatch(page, /backtest|validated|will rise|likely to rise/i);

  const index = "src/lib/market-index.ts";
  assert.equal(num(index, "INDEX_SIZE"), 200);
  assert.equal(num(index, "MAX_WEIGHT_SHARE"), 0.2);
  assert.match(page, /follows the 200 most-searched cards that have a price in the selected market, each weighted by its searches and capped at 20%/);
});

test("the method change the history section dates is the first METHODOLOGY_BREAKS entry", () => {
  const first = METHODOLOGY_BREAKS[0];
  assert.equal(first.from, Date.UTC(2026, 8, 23));
  assert.match(first.why, /TCGplayer/);
  assert.match(text(METHOD), /On 23 September 2026 the US TCGplayer row switched from TCGplayer&rsquo;s market price to its cheapest English listing/);
});

test("/methodology computes its counts, never cites the synthetic market price, and ends on its guides", () => {
  const src = read(METHOD);
  assert.match(src, /RETAILER_LIST\.length/);
  assert.match(src, /SHIPPING_SNAPSHOT\.stores\[r\.key\]\?\.status === "measured"/, "the measured-store count comes from the snapshot");
  assert.match(src, /SHIPPING_SNAPSHOT\.markets\[c\.code\]/, "the probe's addresses come from the snapshot");
  assert.doesNotMatch(code(METHOD), /marketPriceCents/, "Card.marketPriceCents is synthetic (CURRENT-STATE)");
  // "Delivered cost is always shown" was false: card-page store rows quote postage at checkout.
  assert.doesNotMatch(text(METHOD), /always shown alongside/i);
  assert.match(text(METHOD), /cheapest first by item price, with the delivered total shown where the store publishes its postage/);
  const related = src.indexOf('<RelatedGuides guides={guidesForTool("/methodology")} />');
  assert.ok(related > src.indexOf('id="demand-finder"'), "RelatedGuides comes after the page's own content");
});

// ── /privacy ──────────────────────────────────────────────────────────────────

test("/privacy names the analytics, sign-in, email and payment services the code uses", () => {
  const privacy = text(PRIVACY);
  assert.match(read("src/lib/ga.ts"), /GA_MEASUREMENT_ID = \(process\.env\.NEXT_PUBLIC_GA_ID \|\| "G-/);
  assert.match(privacy, /Google Analytics 4/);
  assert.match(privacy, /Consent Mode v2/);
  assert.match(privacy, /Vercel Analytics/);
  assert.match(privacy, /opaque identifier for your account/);
  const names: Record<string, string> = { google: "Google", discord: "Discord" };
  assert.deepEqual([...OAUTH_PROVIDERS].sort(), Object.keys(names).sort(), "a sign-in provider changed — update /privacy");
  assert.match(privacy, /you sign in with Google or Discord/);
  assert.doesNotMatch(privacy, /hashed password you provide|marketplace/i);
  const email = read("src/lib/email.ts");
  assert.match(email, /api\.resend\.com/);
  assert.match(email, /api\.brevo\.com/);
  assert.match(privacy, /Resend/);
  assert.match(privacy, /Brevo/);
  assert.match(privacy, /Stripe/);
  assert.match(privacy, /store consulting sessions are processed by/);
  const ai = read("src/lib/ai-insight.ts");
  assert.match(ai, /@anthropic-ai\/sdk/);
  assert.match(ai, /GEMINI_API_KEY/);
  assert.match(privacy, /Anthropic or Google/);
});

test("every cookie /privacy names is one the code sets, under that name", () => {
  const privacy = text(PRIVACY);
  const cookies: [file: string, name: string][] = [
    ["src/lib/auth.ts", "SESSION_COOKIE"],
    ["src/lib/country.ts", "COUNTRY_COOKIE"],
    ["src/lib/country.ts", "EUR_DISPLAY_COOKIE"],
    ["src/lib/theme-shared.ts", "THEME_COOKIE"],
    ["src/lib/ad-free-boot.ts", "AD_FREE_COOKIE"],
    ["src/lib/referral-cookie.ts", "REFERRAL_COOKIE"],
    ["src/lib/signup-source-shared.ts", "SIGNUP_SOURCE_COOKIE"],
  ];
  for (const [file, name] of cookies) {
    const value = JSON.parse(constant(file, name));
    assert.ok(privacy.includes(`>${value}</code>`), `/privacy must name the ${value} cookie (${name})`);
  }
  assert.match(read("src/app/api/auth/oauth/[provider]/route.ts"), /cookies\(\)\.set\(`oauth_state_\$\{provider\}`[\s\S]{0,200}maxAge: 600/);
  assert.match(privacy, /oauth_state_\*/);
});

// ── /terms ────────────────────────────────────────────────────────────────────

test("/terms covers store consulting, published decks and the snapshot basis, numbered in order", () => {
  const terms = text(TERMS);
  assert.match(terms, /9\. Store consulting/);
  assert.match(terms, /href="\/stores\/consulting"/);
  assert.match(text("src/app/stores/consulting/page.tsx"), /15 minutes in/, "the refund promise /terms repeats lives there");
  assert.match(terms, /15 minutes into the session/);
  assert.match(terms, /Published decks are public/);
  assert.match(terms, /we may hide a deck that breaches these Terms/);
  assert.match(read("src/app/api/admin/decks/route.ts"), /"hidden"/);
  assert.match(terms, /07:00 and 19:00 UTC/);
  assert.match(terms, /Subscription fees already paid are non-refundable/);
  const numbers = [...terms.matchAll(/text-lg font-bold text-white">(\d+)\. /g)].map((m) => Number(m[1]));
  assert.deepEqual(numbers, numbers.map((_, i) => i + 1), "sections must be numbered 1..n in order");
});

test("/terms states no jurisdiction the repo doesn't", () => {
  // Nothing in the codebase names a governing law; choosing one is the owner's
  // call (open question, 2026-09-26). The ACL mention is a consumer-rights
  // carve-out, not a choice of law.
  assert.doesNotMatch(text(TERMS), /governed by the laws|governing law|exclusive jurisdiction/i);
});

// ── /contact and /support ─────────────────────────────────────────────────────

test("/contact and /support say what they are for and promise no response time", () => {
  const contact = text(CONTACT);
  const support = text(SUPPORT);
  assert.match(contact, /<ContactForm \/>/);
  assert.match(contact, /href="\/support"/);
  assert.match(support, /href="\/contact"/);
  assert.match(support, /numbered ticket/);
  assert.match(read("src/app/api/support/route.ts"), /sendSupportTicketConfirmation/);
  for (const [f, t] of [[CONTACT, contact], [SUPPORT, support]] as const) {
    assert.doesNotMatch(t, /within a day or two|within \d+ (hours|days)|usually reply/i, `${f} promises a response time`);
  }
});

// ── All seven ────────────────────────────────────────────────────────────────

test("no trust page carries an in-page affiliate banner pair (owner, 2026-09-26)", () => {
  for (const f of TRUST_PAGES) assert.doesNotMatch(code(f), /<(EbayAd|TcgplayerAd)\b/, f);
});

test("the trust pages keep their cache windows", () => {
  for (const f of [ABOUT, POLICY, METHOD]) assert.match(read(f), /export const revalidate = 86400;/, f);
  assert.doesNotMatch(read(PRIVACY) + read(TERMS) + read(CONTACT), /export const (revalidate|dynamic)/);
  assert.match(read(SUPPORT), /export const dynamic = "force-dynamic";/);
});
