-- 2026-09-26: PublishedDeck (the public deck library, lib/published-decks.ts).
-- ADDITIVE ONLY: one new table, no change to any existing table.
-- Applied by `prisma db push` (scripts/build-db-push.sh); this is the reviewed
-- DDL, generated by `prisma migrate diff` against the previous schema.prisma.

-- CreateTable
CREATE TABLE "PublishedDeck" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "userId" TEXT,
    "authorName" TEXT,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "legendCardId" TEXT NOT NULL,
    "legendName" TEXT NOT NULL,
    "legendSlug" TEXT NOT NULL,
    "domains" TEXT NOT NULL,
    "list" TEXT NOT NULL,
    "lines" JSONB NOT NULL,
    "cardIds" TEXT[],
    "cardCount" INTEGER NOT NULL,
    "publishedTotals" JSONB NOT NULL,
    "source" TEXT NOT NULL DEFAULT 'user',
    "status" TEXT NOT NULL DEFAULT 'live',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PublishedDeck_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "PublishedDeck_slug_key" ON "PublishedDeck"("slug");

-- CreateIndex
CREATE INDEX "PublishedDeck_status_createdAt_idx" ON "PublishedDeck"("status", "createdAt");

-- CreateIndex
CREATE INDEX "PublishedDeck_legendSlug_idx" ON "PublishedDeck"("legendSlug");

-- CreateIndex
CREATE INDEX "PublishedDeck_userId_createdAt_idx" ON "PublishedDeck"("userId", "createdAt");

