-- 2026-09-26: SetReleaseAlert (the Radiance release alert, lib/release-alerts.ts).
-- ADDITIVE ONLY: one new table, no change to any existing table.
-- This repo applies schema with `prisma db push` (scripts/build-db-push.sh on
-- each production build); this file is the reviewed DDL that push produces,
-- generated by `prisma migrate diff` against the previous schema.prisma.

-- CreateTable
CREATE TABLE "SetReleaseAlert" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "setCode" TEXT NOT NULL,
    "scope" TEXT NOT NULL DEFAULT 'set',
    "market" TEXT NOT NULL DEFAULT 'US',
    "source" TEXT,
    "unsubToken" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "singlesNotifiedAt" TIMESTAMP(3),
    "restockNotifiedAt" TIMESTAMP(3),

    CONSTRAINT "SetReleaseAlert_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "SetReleaseAlert_setCode_idx" ON "SetReleaseAlert"("setCode");

-- CreateIndex
CREATE INDEX "SetReleaseAlert_unsubToken_idx" ON "SetReleaseAlert"("unsubToken");

-- CreateIndex
CREATE UNIQUE INDEX "SetReleaseAlert_email_setCode_scope_key" ON "SetReleaseAlert"("email", "setCode", "scope");

