import type { Metadata } from "next";
import { notFoundMetadata } from "@/lib/not-found-metadata";
import { notFound } from "next/navigation";
import { getArticle, getArticles } from "@/lib/articles";
import { getBlogPost, getMarketReportPost } from "@/lib/posts";
import { ArticleView } from "@/components/ArticleView";
import { MarketReportView } from "@/components/MarketReportView";
import { SITE_URL } from "@/lib/site";
import { hreflangForCountryGuide, pageAlternates, pageOpenGraph } from "@/lib/seo";

// Pre-render the file-based posts; DB-backed market reports render on demand
// (dynamicParams defaults to true) and are cached by `revalidate`.
export const revalidate = 600;

export function generateStaticParams() {
  return getArticles("blog").map((a) => ({ slug: a.slug }));
}

export async function generateMetadata({ params }: { params: { slug: string } }): Promise<Metadata> {
  const a = await getBlogPost(params.slug);
  if (!a) return notFoundMetadata("Post");
  // A post with no file-based counterpart is a LEGACY auto-generated market
  // report. Generation is DELETED (see lib/market-report.ts), so this branch only
  // ever matches the ~130 rows already in the DB — there will never be a new one.
  // They stay resolvable by direct URL rather than becoming 404s, but are
  // noindexed (a run of near-identical templated pages is "scaled content abuse"
  // shape); `follow` is kept so their outbound links still pass signal. They are
  // also absent from the sitemap (lib/sitemap-sections.ts) and from /blog, the
  // feeds and the news sitemap (lib/posts.ts getBlogPosts).
  const isAutoGenerated = !getArticle(params.slug);
  return {
    title: { absolute: `${a.title} — RiftCompare Blog` },
    description: a.excerpt,
    ...(isAutoGenerated ? { robots: { index: false, follow: true } } : {}),
    alternates: pageAlternates(`/blog/${a.slug}`, {
      types: { "text/markdown": `${SITE_URL}/llm/blog/${a.slug}` },
      // The six country buying guides are the ONE place on this site where
      // per-market hreflang is honest: each is a separately-indexable page about
      // buying in one market, in that market's currency, and they are genuine
      // alternates of each other. Everywhere else the market is a cookie over a
      // single URL set, so pageAlternates() falls back to x-default only.
      ...(hreflangForCountryGuide(a.slug) ? { languages: hreflangForCountryGuide(a.slug)! } : {}),
    }),
    openGraph: pageOpenGraph({
      type: "article",
      title: a.title,
      description: a.excerpt,
      url: `/blog/${a.slug}`,
      publishedTime: a.date,
      modifiedTime: a.updated ?? a.date,
      authors: [a.author],
      ...(a.hero ? { images: [`${SITE_URL}${a.hero.src}`] } : {}),
    }),
  };
}

export default async function BlogArticlePage({ params }: { params: { slug: string } }) {
  // File-based editorial posts render as plain articles.
  const file = getArticle(params.slug);
  if (file && file.category === "blog") return <ArticleView article={file} />;

  // Market reports get the chart-rich view when their payload is stored; rows
  // that predate the charts fall back to the markdown body.
  const report = await getMarketReportPost(params.slug);
  if (!report) notFound();
  // Daily market reports are timely, dated news → NewsArticle (freshness signal for
  // Google News / AI answer engines, which weight recency heavily).
  const published = `${report.day}T09:00:00+10:00`;
  const newsLd = {
    "@context": "https://schema.org",
    "@type": "NewsArticle",
    headline: report.article.title,
    description: report.article.excerpt,
    datePublished: published,
    dateModified: published,
    author: { "@id": `${SITE_URL}/#org`, name: "RiftCompare" },
    publisher: { "@id": `${SITE_URL}/#org` },
    mainEntityOfPage: `${SITE_URL}/blog/${report.article.slug}`,
    url: `${SITE_URL}/blog/${report.article.slug}`,
    isAccessibleForFree: true,
    articleSection: "Market report",
  };
  // The NewsArticle node is emitted ONLY alongside MarketReportView. The
  // fallback path renders <ArticleView>, which publishes its own BlogPosting —
  // emitting both would put two competing article types on one URL.
  return report.data ? (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(newsLd) }} />
      <MarketReportView article={report.article} data={report.data} />
    </>
  ) : (
    <ArticleView article={report.article} />
  );
}
