"use client";

import { useEffect, useState } from "react";

type Verdict = "BUY" | "HOLD" | "CAUTION" | "UNKNOWN";
type Insight = { verdict: Verdict; label: string; summary: string; source: "ai" | "rules" };

const STYLE: Record<Verdict, { chip: string; ring: string; emoji: string }> = {
  BUY: { chip: "bg-brand-500/20 text-brand-300", ring: "border-brand-500/30", emoji: "🟢" },
  HOLD: { chip: "bg-gold/15 text-gold", ring: "border-gold/25", emoji: "🟡" },
  CAUTION: { chip: "bg-rose-500/15 text-rose-300", ring: "border-rose-500/25", emoji: "🔴" },
  UNKNOWN: { chip: "bg-ink-800 text-slate-400", ring: "border-ink-700", emoji: "🔮" },
};

// "AI Tips" — a funny, narrative buy/hold/wait take on a card. Fetched lazily so it
// never blocks the rest of the card view.
export function AiInsight({ cardId, compact = false }: { cardId: string; compact?: boolean }) {
  const [insight, setInsight] = useState<Insight | null>(null);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    let alive = true;
    fetch(`/api/card/${cardId}/insight`)
      .then((r) => (r.ok ? r.json() : Promise.reject()))
      .then((d) => { if (alive) setInsight(d); })
      .catch(() => { if (alive) setFailed(true); });
    return () => { alive = false; };
  }, [cardId]);

  if (failed) return null;
  const s = insight ? STYLE[insight.verdict] : STYLE.UNKNOWN;

  return (
    <div className={`rounded-xl border ${s.ring} bg-ink-950/40 p-4`}>
      <div className="mb-1.5 flex items-center gap-2">
        <span className="text-base">🤖</span>
        <span className="text-xs font-bold uppercase tracking-wide text-slate-300">AI Tips</span>
        {insight?.source === "ai" ? (
          <span className="chip bg-fuchsia-500/15 text-[10px] font-semibold uppercase tracking-wide text-fuchsia-300">✨ Live AI</span>
        ) : (
          <span className="chip bg-brand-500/10 text-[10px] font-semibold uppercase tracking-wide text-brand-300">Beta</span>
        )}
        {insight && (
          <span className={`ml-auto chip text-[11px] font-bold ${s.chip}`}>{s.emoji} {insight.label}</span>
        )}
      </div>
      {insight ? (
        <p className={`leading-relaxed text-slate-200 ${compact ? "text-sm" : "text-sm"}`}>{insight.summary}</p>
      ) : (
        <div className="flex items-center gap-2 py-1 text-sm text-slate-500">
          <span className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-ink-700 border-t-brand-400" />
          Consulting the market gremlin…
        </div>
      )}
      <p className="mt-2 text-[10px] text-slate-600">Generated by AI for fun — not financial advice. Prices reflect the AU market.</p>
    </div>
  );
}
