"use client";

import { useEffect, useState } from "react";
import { useCountry } from "./CountryProvider";
import { COUNTRIES } from "@/lib/country";

type Verdict = "BUY" | "HOLD" | "CAUTION" | "UNKNOWN";
type Insight = { verdict: Verdict; label: string; summary: string; source: "ai" | "rules" };

const STYLE: Record<Verdict, { chip: string; ring: string; dot: string }> = {
  BUY: { chip: "bg-brand-500/20 text-brand-300", ring: "border-brand-500/30", dot: "bg-up" },
  HOLD: { chip: "bg-gold/15 text-gold", ring: "border-gold/25", dot: "bg-gold" },
  CAUTION: { chip: "bg-rose-500/15 text-rose-300", ring: "border-rose-500/25", dot: "bg-down" },
  UNKNOWN: { chip: "bg-ink-800 text-slate-400", ring: "border-ink-700", dot: "bg-ink-600" },
};

// "Price Take" — a funny, narrative buy/hold/wait read on a card. Fetched lazily
// so it never blocks the rest of the card view.
//
// The heading deliberately does NOT say "AI". It used to be "AI Tips" with a
// "Live AI" badge, which put the technology in the headline of a module whose
// actual subject is the card's price. The disclosure in the footer stays, and
// stays specific: the prose genuinely is LLM-written whenever a key is set (see
// lib/ai-insight.ts), so dropping it would leave AI-generated commentary
// undisclosed — the thing ad reviewers penalise, rather than the labelling.
// Renaming the panel and disclosing authorship are not in tension.
const PANEL_TITLE = "Price Take";
export function PriceTake({ cardId, compact = false }: { cardId: string; compact?: boolean }) {
  const { country } = useCountry();
  const [insight, setInsight] = useState<Insight | null>(null);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    let alive = true;
    setInsight(null);
    setFailed(false);
    fetch(`/api/card/${cardId}/insight?country=${country}`)
      .then((r) => (r.ok ? r.json() : Promise.reject()))
      .then((d) => { if (alive) setInsight(d); })
      .catch(() => { if (alive) setFailed(true); });
    return () => { alive = false; };
  }, [cardId, country]);

  if (failed) return null;
  const s = insight ? STYLE[insight.verdict] : STYLE.UNKNOWN;

  return (
    <div className={`rounded-lg border ${s.ring} bg-ink-950/40 p-4`}>
      <div className="mb-1.5 flex items-center gap-2">
        <span className="text-xs font-bold uppercase tracking-wide text-slate-300">{PANEL_TITLE}</span>
        {/* The old "Live AI" / "Beta" pair leaked the implementation into the UI:
            it told the reader which code path had run, which is not something
            they can act on, and put "AI" back in the header the rename removed.
            A reader who wants to know how the prose is written has the footer. */}
        {insight && (
          <span className={`ml-auto chip inline-flex items-center gap-1.5 text-[11px] font-bold ${s.chip}`}>
            <span className={`h-1.5 w-1.5 rounded-full ${s.dot}`} aria-hidden />
            {insight.label}
          </span>
        )}
      </div>
      {insight ? (
        <p className={`leading-relaxed text-slate-200 ${compact ? "text-sm" : "text-sm"}`}>{insight.summary}</p>
      ) : (
        <div className="flex items-center gap-2 py-1 text-sm text-slate-500">
          <span className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-ink-700 border-t-brand-400" />
          Consulting the market gremlin…
        </div>
      )}
      <p className="mt-2 text-[10px] text-slate-600">Generated by AI for fun — not financial advice. Prices reflect the {COUNTRIES[country].place} market.</p>
    </div>
  );
}
