// Condense raw probe output (scripts/probe-shipping-rates.ts) into the postage
// snapshot the site imports: src/lib/shipping-rates.json.
//
// Usage:
//   npx tsx scripts/build-shipping-rates.ts AU.json US.json UK.json CA.json EU.json SG.json
//   npx tsx scripts/build-shipping-rates.ts shipping-au.json --summary=diff.md
//   npx tsx scripts/build-shipping-rates.ts shipping-au.json --out=/tmp/new.json --check
// Options:
//   --out=<path>      where to write (default src/lib/shipping-rates.json)
//   --base=<path>     the snapshot to merge into (default: the --out file, if it exists).
//                     Only the markets present in the inputs are replaced; the
//                     others are kept as they were.
//   --summary=<path>  also write the change report as Markdown (for $GITHUB_STEP_SUMMARY)
//   --check           write nothing to --out; just report what would change
//
// The raw files are several MB each and are NOT committed — the probe workflow
// (.github/workflows/shipping-rates.yml) uploads them as an artifact. Only the
// condensed snapshot is checked in. See lib/shipping-snapshot.ts for its shape
// and lib/shipping.ts for how it is read.
export {};
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { RETAILER_LIST } from "../src/lib/retailers";
import type { Country } from "../src/lib/country";
import { PROBE_ADDRESSES } from "../src/lib/shipping-probe";
import { condenseStore, type ProbeStoreInput, type ShippingSnapshot } from "../src/lib/shipping-snapshot";
import { shippingFor, shippingSummary, formatMeasuredDate } from "../src/lib/shipping";
import { formatMoney } from "../src/lib/format";

function arg(name: string): string | undefined {
  const hit = process.argv.slice(2).find((a) => a === `--${name}` || a.startsWith(`--${name}=`));
  if (!hit) return undefined;
  const eq = hit.indexOf("=");
  return eq < 0 ? "" : hit.slice(eq + 1);
}

const inputs = process.argv.slice(2).filter((a) => !a.startsWith("--"));
if (!inputs.length) {
  console.error("Usage: npx tsx scripts/build-shipping-rates.ts <probe-output.json>... [--out=] [--base=] [--summary=] [--check]");
  process.exit(2);
}
const outPath = resolve(arg("out") || "src/lib/shipping-rates.json");
const basePath = arg("base") ? resolve(arg("base")!) : outPath;
const check = arg("check") !== undefined;

const base: ShippingSnapshot | null = existsSync(basePath) ? JSON.parse(readFileSync(basePath, "utf8")) : null;
const next: ShippingSnapshot = {
  version: 1,
  note:
    "GENERATED by scripts/build-shipping-rates.ts from scripts/probe-shipping-rates.ts runs — do not hand-edit. " +
    "Per store: the carts measured ([subtotalCents, items]) and, per group of addresses quoted identically, the cheapest " +
    "non-letter rate (std: [cents, nameIndex, tracked]) and cheapest untracked letter (ltr: [cents, nameIndex]) for each cart. " +
    "Read by src/lib/shipping.ts.",
  markets: { ...(base?.markets ?? {}) },
  stores: { ...(base?.stores ?? {}) },
};

const replaced = new Set<Country>();
for (const f of inputs) {
  const raw = JSON.parse(readFileSync(resolve(f), "utf8")) as { market: Country; stores: ProbeStoreInput[] };
  const market = raw.market;
  if (!PROBE_ADDRESSES[market as keyof typeof PROBE_ADDRESSES]) throw new Error(`${f}: unknown market ${market}`);
  if (!replaced.has(market)) {
    // A market's stores are replaced as a whole, so a store dropped from
    // retailers.ts since the last run does not linger.
    for (const [k, s] of Object.entries(next.stores)) if (s.market === market) delete next.stores[k];
    replaced.add(market);
  }
  const dates: string[] = [];
  for (const s of raw.stores) {
    next.stores[s.key] = condenseStore({ ...s, market });
    dates.push(next.stores[s.key].measuredAt);
  }
  dates.sort();
  next.markets[market] = {
    measuredAt: dates[dates.length - 1] ?? "",
    addresses: PROBE_ADDRESSES[market as keyof typeof PROBE_ADDRESSES].map((a) => ({ id: a.id, label: a.label })),
  };
}

// Keep only stores that are still configured, in a stable order.
const configured = new Set(RETAILER_LIST.map((r) => r.key));
const gone = Object.keys(next.stores).filter((k) => !configured.has(k));
for (const k of gone) delete next.stores[k];
next.stores = Object.fromEntries(Object.entries(next.stores).sort(([a], [b]) => a.localeCompare(b)));
const missing = RETAILER_LIST.filter((r) => !next.stores[r.key]).map((r) => r.key);

// ── Change report ───────────────────────────────────────────────────────────
const lines: string[] = [];
const fmt = (c: number | null | undefined, cur: string) => (c == null ? "—" : formatMoney(c, cur));
const oneLine = (snap: ShippingSnapshot | null, key: string): string => {
  if (!snap?.stores[key]) return "not in snapshot";
  const s = shippingSummary(key, snap);
  if (s.basis === "no-post") return `no postage (${s.note ?? "does not post"})`;
  if (s.basis === "estimate") return `not measured${s.note ? ` (${s.note})` : ""}`;
  const q = shippingFor(key, { subtotalCents: s.oneCardSubtotalCents ?? 100, items: 1 }, {}, snap);
  const free = s.free?.fromCents != null ? `free from ${fmt(s.free.fromCents, s.currency)}` : "no free threshold";
  return `1 card ${q.upTo ? "up to " : ""}${fmt(q.cents, s.currency)} (${q.label}) · ${free}`;
};
lines.push(`## Postage snapshot — ${[...replaced].join(", ")}`);
lines.push("");
lines.push("| Store | Market | Before | After |");
lines.push("|---|---|---|---|");
let changed = 0;
for (const key of Object.keys(next.stores)) {
  if (!replaced.has(next.stores[key].market)) continue;
  const before = oneLine(base, key);
  const after = oneLine(next, key);
  if (before === after) continue;
  changed++;
  lines.push(`| ${key} | ${next.stores[key].market} | ${before} | ${after} |`);
}
if (!changed) lines.push("| — | — | no change | — |");
lines.push("");
for (const m of replaced) {
  const info = next.markets[m];
  if (info) lines.push(`- ${m}: measured ${formatMeasuredDate(info.measuredAt)}`);
}
if (gone.length) lines.push(`- Dropped (no longer in retailers.ts): ${gone.join(", ")}`);
if (missing.length) lines.push(`- Not in the snapshot (shown as estimates): ${missing.join(", ")}`);
const report = lines.join("\n") + "\n";
console.log(report);
const summaryPath = arg("summary");
if (summaryPath) writeFileSync(resolve(summaryPath), report, { flag: "a" });

// One store per line: small, and a refresh diffs store by store in git.
const json =
  "{\n" +
  `"version": ${next.version},\n"note": ${JSON.stringify(next.note)},\n"markets": ${JSON.stringify(next.markets)},\n"stores": {\n` +
  Object.entries(next.stores)
    .map(([k, v]) => `${JSON.stringify(k)}: ${JSON.stringify(v)}`)
    .join(",\n") +
  "\n}\n}\n";
if (check) {
  console.log(`--check: ${changed} store(s) would change; nothing written (${(json.length / 1024).toFixed(1)} KB).`);
} else {
  writeFileSync(outPath, json);
  console.log(`Wrote ${outPath} (${(json.length / 1024).toFixed(1)} KB, ${Object.keys(next.stores).length} stores).`);
}
